spring:
  application:
    name: boo-mackt
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/boo_market?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:boo-market-secret-key-must-be-longer-than-32-bytes}

sendgrid:
  api-key: ${SENDGRID_API_KEY}
